libraries:
  - name: TV
    type: series
    root: /media/storage/data/media/tv

  - name: Anime
    type: anime
    root: /media/storage/data/media/anime

  - name: DocuSeries
    type: docuseries
    root: /media/storage/data/media/documentaries_tv

  - name: Documentaries
    type: documentary
    root: /media/storage/data/media/documentaries_mov

  - name: Movies
    type: movies
    root: /media/storage/data/media/movies

  - name: Movies3D
    type: movies
    root: /media/storage/data/media/movies_3d
