libraries:
  # ---- Series ----

  - name: SeriesDisk1
    type: series
    root: /media/disk1/Series
  - name: SeriesDisk2
    type: series
    root: /media/disk2/Series

  # ---- Anime ----

  - name: AnimeDisk1
    type: anime
    root: /media/disk1/Anime
  - name: AnimeDisk2
    type: anime
    root: /media/disk2/Anime

  # ---- Documentary Series ----

  - name: DocumentarySeriesDisk1
    type: docuseries
    root: /media/disk1/series_documental
  - name: DocumentarySeriesDisk2
    type: docuseries
    root: /media/disk2/series_documental

  # ---- Movies ----
  
  - name: MoviesDisk1
    type: movies
    root: /media/disk1/Peliculas
  - name: MoviesDisk2
    type: movies
    root: /media/disk2/Peliculas

  # ---- Documentary Movies ----

  - name: DocumentaryMoviesDisk1
    type: documentary
    root: /media/disk1/Documentales
  - name: DocumentaryMoviesDisk2
    type: documentary
    root: /media/disk2/Documentales



